# -*- coding: utf-8 -*-
"""face_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10SMIAX7gR1rTABrdETVqzI10Bl4S6ykQ
"""

!pip install face_recognition

"""# ライブラリーのインポート"""

import sys
import face_recognition
import cv2
import numpy as np
from PIL.Image import core as _imaging
from PIL import ImageFont, ImageDraw, Image
import glob

face_locations = []

video_capture = cv2.VideoCapture(0)

def main():
    while True:
        #ビデオの単一フレームを取得
        _, frame = video_capture.read()

        #顔の位置情報を検索
        face_locations = face_recognition. face_locations(frame)

        #位置情報の表示
        for (top, right, bottom, left) in face_locations:
            #顔領域に枠を描画
            cv2. rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)


        #結果をビデオに表示
        cv2.imshow('Video', frame)

        #ESCキーで終了
        if cv2.waitKey(1) == 27:
            break

main()

video_capture.release()
cv2.destroyAllWindows()